Search.appendIndex(
    [
                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB",
            "name": "ConnectionDB",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020of\u0020ConnectionDB.",
            "url": "classes/hakuryo-db-ConnectionDB.html#method___construct"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Afrom_file\u0028\u0029",
            "name": "from_file",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020of\u0020ConnectionDB\u0020from\u0020a\u0020ini\u0020file.",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_from_file"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Perform\u0020a\u0020SELECT\/SHOW\/DESCRIB\u0020request\u0020and\u0020expect\u0020multiple\u0020results",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_search"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Perform\u0020a\u0020SELECT\/SHOW\/DESCRIB\u0020request\u0020and\u0020get\u0020the\u0020first\u0020result",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_get"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Amodify\u0028\u0029",
            "name": "modify",
            "summary": "Perform\u0020a\u0020UPDATE\/INSERT\/DELETE\u0020and\u0020return\u0020the\u0020number\u0020of\u0020affected\u0020rows",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_modify"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Ais_oci\u0028\u0029",
            "name": "is_oci",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_is_oci"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Abind_values\u0028\u0029",
            "name": "bind_values",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_bind_values"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Acheck_query_type\u0028\u0029",
            "name": "check_query_type",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_check_query_type"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Acast_data\u0028\u0029",
            "name": "cast_data",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_cast_data"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Afecth_data\u0028\u0029",
            "name": "fecth_data",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_fecth_data"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003Aget_casted_value\u0028\u0029",
            "name": "get_casted_value",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html#method_get_casted_value"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003AQUERY_TYPE_SEARCH",
            "name": "QUERY_TYPE_SEARCH",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html#constant_QUERY_TYPE_SEARCH"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDB\u003A\u003AQUERY_TYPE_MODIFY",
            "name": "QUERY_TYPE_MODIFY",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDB.html#constant_QUERY_TYPE_MODIFY"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDBUtils",
            "name": "ConnectionDBUtils",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDBUtils.html"
        },                {
            "fqsen": "\\hakuryo\\db\\ConnectionDBUtils\u003A\u003Aparse_ini\u0028\u0029",
            "name": "parse_ini",
            "summary": "",
            "url": "classes/hakuryo-db-ConnectionDBUtils.html#method_parse_ini"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP",
            "name": "ConnectionLDAP",
            "summary": "Description\u0020of\u0020ConnectionLDAP",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020instance\u0020of\u0020ConnectionLDAP",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method___construct"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003AfromFile\u0028\u0029",
            "name": "fromFile",
            "summary": "Create\u0020a\u0020instance\u0020of\u0020ConnectionLDAP\u0020from\u0020a\u0020ini\u0020file.",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method_fromFile"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Retourne\u0020le\u0020resultat\u0020de\u0020\u0024filter\u0020avec\u0020les\u0020attribut\u0020specifie\u0020dans\u0020\u0024returnedAttrs.",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method_search"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003Aget_entry\u0028\u0029",
            "name": "get_entry",
            "summary": "Retourne\u0020l\u0027entree\u0020corespondant\u0020a\u0020\u0024filter\u0020avec\u0020les\u0020attributs\u0020specifie\u0020dans\u0020\u0024returnedAttrs.",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method_get_entry"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003Amodify\u0028\u0029",
            "name": "modify",
            "summary": "Modify\u0020a\u0020LDAP\u0020entry",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method_modify"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Create\u0020an\u0020LDAP\u0020entry",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method_add"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020the\u0020ldap\u0020entry\u0020specified\u0020by\u0020\u0024entry_dn",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method_delete"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003Adisconect\u0028\u0029",
            "name": "disconect",
            "summary": "Close\u0020the\u0020ldap\u0020connection",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method_disconect"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003Aget_search_options\u0028\u0029",
            "name": "get_search_options",
            "summary": "",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#method_get_search_options"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003AMOD_ADD",
            "name": "MOD_ADD",
            "summary": "",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#constant_MOD_ADD"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003AMOD_REPLACE",
            "name": "MOD_REPLACE",
            "summary": "",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#constant_MOD_REPLACE"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003AMOD_DEL",
            "name": "MOD_DEL",
            "summary": "",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#constant_MOD_DEL"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#property_connection"
        },                {
            "fqsen": "\\hakuryo\\ldap\\ConnectionLDAP\u003A\u003A\u0024search_options",
            "name": "search_options",
            "summary": "",
            "url": "classes/hakuryo-ldap-ConnectionLDAP.html#property_search_options"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions",
            "name": "LdapSearchOptions",
            "summary": "Description\u0020of\u0020LdapSearchOptions",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#method___construct"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003Aset_base_dn\u0028\u0029",
            "name": "set_base_dn",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#method_set_base_dn"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003Aset_result_limit\u0028\u0029",
            "name": "set_result_limit",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#method_set_result_limit"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003Aset_scope\u0028\u0029",
            "name": "set_scope",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#method_set_scope"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003Aget_base_dn\u0028\u0029",
            "name": "get_base_dn",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#method_get_base_dn"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003Aget_result_limit\u0028\u0029",
            "name": "get_result_limit",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#method_get_result_limit"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003Aget_scope\u0028\u0029",
            "name": "get_scope",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#method_get_scope"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003ASEARCH_SCOPE_SUB",
            "name": "SEARCH_SCOPE_SUB",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#constant_SEARCH_SCOPE_SUB"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003ASEARCH_SCOPE_ONE_LEVEL",
            "name": "SEARCH_SCOPE_ONE_LEVEL",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#constant_SEARCH_SCOPE_ONE_LEVEL"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003A\u0024base_dn",
            "name": "base_dn",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#property_base_dn"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003A\u0024result_limit",
            "name": "result_limit",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#property_result_limit"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapSearchOptions\u003A\u003A\u0024scope",
            "name": "scope",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapSearchOptions.html#property_scope"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapUtils",
            "name": "LdapUtils",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapUtils.html"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapUtils\u003A\u003Aclear_ldap_result\u0028\u0029",
            "name": "clear_ldap_result",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapUtils.html#method_clear_ldap_result"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapUtils\u003A\u003Acreate_groupOfNames\u0028\u0029",
            "name": "create_groupOfNames",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapUtils.html#method_create_groupOfNames"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapUtils\u003A\u003Aformat_password\u0028\u0029",
            "name": "format_password",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapUtils.html#method_format_password"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapUtils\u003A\u003Aget_root_dn\u0028\u0029",
            "name": "get_root_dn",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapUtils.html#method_get_root_dn"
        },                {
            "fqsen": "\\hakuryo\\ldap\\LdapUtils\u003A\u003AgetLastError\u0028\u0029",
            "name": "getLastError",
            "summary": "",
            "url": "classes/hakuryo-ldap-LdapUtils.html#method_getLastError"
        },                {
            "fqsen": "\\Utils",
            "name": "Utils",
            "summary": "Description\u0020of\u0020Utils",
            "url": "classes/Utils.html"
        },                {
            "fqsen": "\\Utils\u003A\u003Aparse_ini\u0028\u0029",
            "name": "parse_ini",
            "summary": "",
            "url": "classes/Utils.html#method_parse_ini"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\hakuryo\\db",
            "name": "db",
            "summary": "",
            "url": "namespaces/hakuryo-db.html"
        },                {
            "fqsen": "\\hakuryo",
            "name": "hakuryo",
            "summary": "",
            "url": "namespaces/hakuryo.html"
        },                {
            "fqsen": "\\hakuryo\\ldap",
            "name": "ldap",
            "summary": "",
            "url": "namespaces/hakuryo-ldap.html"
        }            ]
);
